# Generated by cpp11: do not edit by hand

format_jdate_cpp <- function(x, format) {
  .Call(`_shide_format_jdate_cpp`, x, format)
}

format_jdatetime_cpp <- function(x, format) {
  .Call(`_shide_format_jdatetime_cpp`, x, format)
}

jdate_make_cpp <- function(fields) {
  .Call(`_shide_jdate_make_cpp`, fields)
}

jdatetime_make_cpp <- function(fields, tzone) {
  .Call(`_shide_jdatetime_make_cpp`, fields, tzone)
}

jdate_parse_cpp <- function(x, format) {
  .Call(`_shide_jdate_parse_cpp`, x, format)
}

jdatetime_parse_cpp <- function(x, format, tzone) {
  .Call(`_shide_jdatetime_parse_cpp`, x, format, tzone)
}

sys_seconds_from_local_days_cpp <- function(x, tzone) {
  .Call(`_shide_sys_seconds_from_local_days_cpp`, x, tzone)
}

local_days_from_sys_seconds_cpp <- function(x, tzone) {
  .Call(`_shide_local_days_from_sys_seconds_cpp`, x, tzone)
}
