# Generated by cpp11: do not edit by hand

jdate_get_fields_cpp <- function(x) {
  .Call(`_shide_jdate_get_fields_cpp`, x)
}

jdatetime_get_fields_cpp <- function(x) {
  .Call(`_shide_jdatetime_get_fields_cpp`, x)
}

jdate_get_yday_cpp <- function(x) {
  .Call(`_shide_jdate_get_yday_cpp`, x)
}

jdate_get_wday_cpp <- function(x) {
  .Call(`_shide_jdate_get_wday_cpp`, x)
}

jdate_get_qday_cpp <- function(x) {
  .Call(`_shide_jdate_get_qday_cpp`, x)
}

format_jdate_cpp <- function(x, format) {
  .Call(`_shide_format_jdate_cpp`, x, format)
}

format_jdatetime_cpp <- function(x, format) {
  .Call(`_shide_format_jdatetime_cpp`, x, format)
}

year_is_leap_cpp <- function(x) {
  .Call(`_shide_year_is_leap_cpp`, x)
}

jdate_make_cpp <- function(fields) {
  .Call(`_shide_jdate_make_cpp`, fields)
}

jdatetime_make_cpp <- function(fields, tzone, ambiguous) {
  .Call(`_shide_jdatetime_make_cpp`, fields, tzone, ambiguous)
}

jdatetime_make_with_reference_cpp <- function(fields, tzone, x) {
  .Call(`_shide_jdatetime_make_with_reference_cpp`, fields, tzone, x)
}

jdate_parse_cpp <- function(x, format) {
  .Call(`_shide_jdate_parse_cpp`, x, format)
}

jdatetime_parse_cpp <- function(x, format, tzone, ambiguous) {
  .Call(`_shide_jdatetime_parse_cpp`, x, format, tzone, ambiguous)
}

jdate_ceiling_cpp <- function(x, unit_name) {
  .Call(`_shide_jdate_ceiling_cpp`, x, unit_name)
}

jdate_floor_cpp <- function(x, unit_name, n) {
  .Call(`_shide_jdate_floor_cpp`, x, unit_name, n)
}

parse_unit_cpp <- function(unit) {
  .Call(`_shide_parse_unit_cpp`, unit)
}

jdate_seq_by_month_cpp <- function(x, dm) {
  .Call(`_shide_jdate_seq_by_month_cpp`, x, dm)
}

jdate_seq_by_year_cpp <- function(x, dy) {
  .Call(`_shide_jdate_seq_by_year_cpp`, x, dy)
}

sys_seconds_from_local_days_cpp <- function(x, tzone) {
  .Call(`_shide_sys_seconds_from_local_days_cpp`, x, tzone)
}

local_days_from_sys_seconds_cpp <- function(x, tzone) {
  .Call(`_shide_local_days_from_sys_seconds_cpp`, x, tzone)
}

get_local_info_cpp <- function(x, tzone) {
  .Call(`_shide_get_local_info_cpp`, x, tzone)
}

get_sys_info_cpp <- function(x) {
  .Call(`_shide_get_sys_info_cpp`, x)
}
